<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str; 
class SubmissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          DB::table('submissions')->insert([
    [
        'id' => Str::ulid(), 
        'user_id' => Str::ulid(), 
        'name' => 'John Doe',
        'phone' => '+1234567890',
        'email' => 'john.doe@example.com',
        'property' => 'The Valeron Tower',
        'type' => 'Apartment',
        'location' => 'Downtown City',
        'price' => 250000.00,
        'area' => 1200,
        'parking' => true,
        'vacant' => false,
        'nearby' => 'Park, Shopping Mall, School',
        'description' => 'Spacious 2-bedroom apartment with modern amenities.',
        'sale' => 'For Sale',
        'badge' => 'New Listing',
        'status' => 'Active',
        'submit_status' => 'Submitted',
        'unit_number' => 'A-10',
        'unit_type' => '2 Bedroom',
        'unit_furnish' => 'Semi-furnished',
        'unit_floor' => '10',
        'submitted_by' => 'admin',
        'commission' => true,
        'terms' => '30% upfront payment',
        'title' => 'Modern 2-Bedroom Apartment for Sale',
        'turnover' => '2025-06-01',
        'lease' => '3 years',
        'acknowledgment' => true,
        'images' => json_encode(['image1.jpg', 'image2.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Jane Smith',
        'phone' => '+9876543210',
        'email' => 'jane.smith@example.com',
        'property' => 'Oak Harbor Residences',
        'type' => 'Condo',
        'location' => 'Bay Area',
        'price' => 320000.00,
        'area' => 950,
        'parking' => true,
        'vacant' => true,
        'nearby' => 'Beach, Supermarket, Hospital',
        'description' => 'Cozy one-bedroom condo with scenic ocean view.',
        'sale' => 'For Rent',
        'badge' => 'Featured',
        'status' => 'Active',
        'submit_status' => 'Pending',
        'unit_number' => 'B-5',
        'unit_type' => '1 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => '5',
        'submitted_by' => 'agent1',
        'commission' => false,
        'terms' => '1-year lease agreement',
        'title' => 'Oceanfront Condo for Rent',
        'turnover' => '2024-08-15',
        'lease' => '1 year',
        'acknowledgment' => false,
        'images' => json_encode(['image3.jpg', 'image4.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Emily Brown',
        'phone' => '+1122334455',
        'email' => 'emily.brown@example.com',
        'property' => 'Sage Residence',
        'type' => 'Townhouse',
        'location' => 'Green Valley',
        'price' => 450000.00,
        'area' => 1500,
        'parking' => true,
        'vacant' => false,
        'nearby' => 'Park, School, Library',
        'description' => 'Charming 3-bedroom townhouse with garden space.',
        'sale' => 'For Sale',
        'badge' => 'Exclusive',
        'status' => 'Active',
        'submit_status' => 'Submitted',
        'unit_number' => 'D-7',
        'unit_type' => '3 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => 'N/A',
        'submitted_by' => 'admin',
        'commission' => true,
        'terms' => '20% upfront payment',
        'title' => 'Spacious Townhouse for Sale',
        'turnover' => '2025-02-28',
        'lease' => '3 years',
        'acknowledgment' => true,
        'images' => json_encode(['image5.jpg', 'image6.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Michael Johnson',
        'phone' => '+2233445566',
        'email' => 'michael.johnson@example.com',
        'property' => 'Mulberry Place',
        'type' => 'Apartment',
        'location' => 'Uptown City',
        'price' => 370000.00,
        'area' => 1300,
        'parking' => true,
        'vacant' => true,
        'nearby' => 'Shopping Mall, Restaurant, Gym',
        'description' => 'Modern 2-bedroom apartment with city views.',
        'sale' => 'For Sale',
        'badge' => 'Featured',
        'status' => 'Active',
        'submit_status' => 'Pending',
        'unit_number' => 'C-3',
        'unit_type' => '2 Bedroom',
        'unit_furnish' => 'Partially-furnished',
        'unit_floor' => '8',
        'submitted_by' => 'admin',
        'commission' => false,
        'terms' => '40% upfront payment',
        'title' => 'City View 2-Bedroom Apartment',
        'turnover' => '2025-07-15',
        'lease' => '2 years',
        'acknowledgment' => false,
        'images' => json_encode(['image7.jpg', 'image8.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Sarah Wilson',
        'phone' => '+3344556677',
        'email' => 'sarah.wilson@example.com',
        'property' => 'Moncello Crest',
        'type' => 'Condo',
        'location' => 'Seaside Town',
        'price' => 280000.00,
        'area' => 1100,
        'parking' => false,
        'vacant' => true,
        'nearby' => 'Beach, Supermarket, Hospital',
        'description' => '1-bedroom condo with oceanfront view.',
        'sale' => 'For Rent',
        'badge' => 'Popular',
        'status' => 'Active',
        'submit_status' => 'Pending',
        'unit_number' => 'E-1',
        'unit_type' => '1 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => '3',
        'submitted_by' => 'agent2',
        'commission' => false,
        'terms' => '1-year lease agreement',
        'title' => 'Oceanfront Condo for Rent',
        'turnover' => '2024-09-01',
        'lease' => '1 year',
        'acknowledgment' => true,
        'images' => json_encode(['image9.jpg', 'image10.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'David Lee',
        'phone' => '+5566778899',
        'email' => 'david.lee@example.com',
        'property' => 'Prisma Residence',
        'type' => 'Apartment',
        'location' => 'Central Park Area',
        'price' => 380000.00,
        'area' => 1400,
        'parking' => true,
        'vacant' => true,
        'nearby' => 'Park, School, Subway',
        'description' => '3-bedroom apartment with garden view.',
        'sale' => 'For Sale',
        'badge' => 'New Listing',
        'status' => 'Active',
        'submit_status' => 'Submitted',
        'unit_number' => 'F-4',
        'unit_type' => '3 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => '12',
        'submitted_by' => 'admin',
        'commission' => true,
        'terms' => '25% upfront payment',
        'title' => '3-Bedroom Apartment for Sale',
        'turnover' => '2025-05-01',
        'lease' => '3 years',
        'acknowledgment' => true,
        'images' => json_encode(['image11.jpg', 'image12.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Olivia Green',
        'phone' => '+6677889900',
        'email' => 'olivia.green@example.com',
        'property' => 'Allegra Garden Place',
        'type' => 'House',
        'location' => 'Riverside Area',
        'price' => 550000.00,
        'area' => 2000,
        'parking' => true,
        'vacant' => false,
        'nearby' => 'Park, School, River',
        'description' => 'Luxury 4-bedroom house with garden and pool.',
        'sale' => 'For Sale',
        'badge' => 'Exclusive',
        'status' => 'Active',
        'submit_status' => 'Submitted',
        'unit_number' => 'G-2',
        'unit_type' => '4 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => 'N/A',
        'submitted_by' => 'admin',
        'commission' => true,
        'terms' => '50% upfront payment',
        'title' => 'Luxury 4-Bedroom House for Sale',
        'turnover' => '2025-10-15',
        'lease' => '5 years',
        'acknowledgment' => true,
        'images' => json_encode(['image13.jpg', 'image14.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Lucas White',
        'phone' => '+7788990011',
        'email' => 'lucas.white@example.com',
        'property' => 'The Oriana',
        'type' => 'Apartment',
        'location' => 'City Center',
        'price' => 420000.00,
        'area' => 1300,
        'parking' => true,
        'vacant' => true,
        'nearby' => 'Mall, Bank, Public Transport',
        'description' => '2-bedroom apartment with a view of the city skyline.',
        'sale' => 'For Rent',
        'badge' => 'Featured',
        'status' => 'Active',
        'submit_status' => 'Pending',
        'unit_number' => 'H-6',
        'unit_type' => '2 Bedroom',
        'unit_furnish' => 'Semi-furnished',
        'unit_floor' => '7',
        'submitted_by' => 'agent3',
        'commission' => false,
        'terms' => '6-month lease agreement',
        'title' => 'City View 2-Bedroom Apartment for Rent',
        'turnover' => '2024-12-01',
        'lease' => '6 months',
        'acknowledgment' => true,
        'images' => json_encode(['image15.jpg', 'image16.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'id' => Str::ulid(),
        'user_id' => Str::ulid(),
        'name' => 'Ava Parker',
        'phone' => '+8899001122',
        'email' => 'ava.parker@example.com',
        'property' => 'Fortis Residence',
        'type' => 'Condo',
        'location' => 'Northside City',
        'price' => 500000.00,
        'area' => 1450,
        'parking' => true,
        'vacant' => false,
        'nearby' => 'Restaurant, Hospital, School',
        'description' => '3-bedroom condo with a panoramic view of the city.',
        'sale' => 'For Rent',
        'badge' => 'Popular',
        'status' => 'Active',
        'submit_status' => 'Pending',
        'unit_number' => 'I-8',
        'unit_type' => '3 Bedroom',
        'unit_furnish' => 'Fully-furnished',
        'unit_floor' => '11',
        'submitted_by' => 'admin',
        'commission' => false,
        'terms' => '1-year lease agreement',
        'title' => 'Panoramic City View Condo for Rent',
        'turnover' => '2025-01-15',
        'lease' => '1 year',
        'acknowledgment' => false,
        'images' => json_encode(['image17.jpg', 'image18.jpg']),
        'amenities' => json_encode(['Swimming Pool', 'Gym', 'Club House', 'Spa', 'Jogging Track', 'Tennis Court', 'Children\'s Play Area', 'Lounge', 'Barbecue Area', 'Rooftop Garden', 'Business Center', 'Party Hall', 'Indoor Games Room', 'Security System', '24/7 Water Supply', 'Wi-Fi Connectivity', 'Shuttle Service', 'Electric Vehicle Charging', 'Parking Lot', 'Café', 'Convenience Store', 'Health Clinic', 'Pet Area', 'Library', 'Billiards Room']),

        'created_at' => now(),
        'updated_at' => now(),
    ],
]);
    }
}
